// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: reports.sql

package db

import (
	"context"
)

const newReport = `-- name: NewReport :exec
INSERT INTO report(file_uuid, reason)
VALUES($1, $2)
`

type NewReportParams struct {
	FileUuid string
	Reason   string
}

func (q *Queries) NewReport(ctx context.Context, arg NewReportParams) error {
	_, err := q.db.Exec(ctx, newReport, arg.FileUuid, arg.Reason)
	return err
}
