version: "3.8"

services:
  db:
    image: "postgres:14.5"
    restart: always

    environment:
      PGPORT: ${DB_PORT:-5432}
      POSTGRES_USER: ${DB_USERNAME:-usva}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-usva}

    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

    expose:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

    volumes:
      - "${CACHE_DIR:-./.postgres-data-dev}:/var/lib/postgresql/data:rw"

