// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Feedback struct {
	ID      int32
	Comment sql.NullString
	Boxes   string
}

type File struct {
	FileUuid     string
	Title        sql.NullString
	Passwdhash   sql.NullString
	Uploader     sql.NullString
	AccessToken  string
	Encrypted    bool
	EncryptionIv []byte
	UploadDate   time.Time
	LastSeen     time.Time
	Viewcount    int32
}

type Report struct {
	FileUuid string
	Reason   string
}
